package org.example;

import org.apache.commons.lang3.StringUtils;

import javax.xml.stream.events.StartDocument;
import java.util.Set;

public class TgwTehtarTextMethods {
    public static String tehtarizeVowels(String inputText) {
        //these replacements must be done simulateneously, not one after another, hence the use of StringUtils.replaceEach()
        String[] rawChars = new String[]{"]", "l", "`", "h", ".", "i"};
        String[] fixedChars = new String[]{"`C", "`V", "`B", "`N", "`M", "`×"};
        //        return inputText
//                .replace("]","`C")//a
//                .replace("l","`V")//e
//                .replace("`","`B")//i
//                .replace("h","`N")//o
//                .replace(".","`M")//u
//                .replace("i","`×")//y
//                ;
        return StringUtils.replaceEach(inputText, rawChars, fixedChars);
    }

    public static String fixDiphtongs(String inputText) { //technically, any two vowels next to each other
        /*
        aa ea ia oa ua ya
        ae ee ie oe ue ye
        ao eo io oo uo yo
        au eu iu ou uu yu
         */
        String[] rawChars = new String[]{
                "`C`C",                "`V`C",
                "`B`C",                "`N`C",
                "`M`C",                "`×`C",
                "`C`V",                "`V`V",
                "`B`V",                "`N`V",
                "`M`V",                "`×`V",
                "`C`N",                "`V`N",
                "`B`N",                "`N`N",
                "`M`N",                "`×`N",
                "`C`M",                "`B`M",
                "`V`M",                "`N`M",
                "`M`M",                "`×`M",
                "`B`B",                "`×`×"
        };

        String[] fixedChars = new String[]{
                "~C", "]R",
                "]T", "]N",
                "]J", "]Õ",
                "lE", "~V",
                "lT", "lN",
                "lJ", "lÕ",
                "hE", "hR",
                "hT", "~N",
                "hJ", "hÕ",
                ".E", ".T",
                ".R", ".N",
                "~M", ".Õ",
                "~B", "~×",

        };
       /* return inputText
                .replace("`C`C", "~C")//long carrier + tehta; aa
                .replace("`V`C", "]R")//hardcoded ea
                .replace("`B`C", "]T")//hardcoded ia
                .replace("`N`C", "]N")//hardcoded oa
                .replace("`M`C", "]J")//hardcoded ua
                .replace("`×`C", "]Õ")//hardcoded ya

                .replace("`C`V", "lE")//hardcoded ae
                .replace("`V`V", "~V")//ee
                .replace("`B`V", "lT")//hardcoded ie
                .replace("`N`V", "lN")//hardcoded oe
                .replace("`M`V", "lJ")//hardcoded ue
                .replace("`×`V", "lÕ")//hardcoded ye

                .replace("`C`N", "hE")//hardcoded ao
                .replace("`V`N", "hR")//hardcoded eo
                .replace("`B`N", "hT")//hardcoded io
                .replace("`N`N", "~N")//oo
                .replace("`M`N", "hJ")//hardcoded uo
                .replace("`×`N", "hÕ")//hardcoded yo

                .replace("`C`M", ".E")//hardcoded au
                .replace("`B`M", ".T")//hardcoded iu
                .replace("`V`M", ".R")//hardcoded eu
                .replace("`N`M", ".N")//hardcoded ou
                .replace("`M`M", "~M")//uu
                .replace("`×`M", ".Õ")//hardcoded yu

                .replace("`B`B", "~B")//ii
                .replace("`×`×", "~×")//yy
                ;*/
        return StringUtils.replaceEach(inputText, rawChars, fixedChars);

    }

    public static String desiSwapTehtar(String input) {
        Set<Character> vowelTehtarOnCarrierSet = Charsets.initVowelTehtaOnCarrierSet();
        StringBuilder result = new StringBuilder();
        String[] inputAsStrings = input.split("`");
        for (String inputSplitElement : inputAsStrings) {
            if (!inputSplitElement.equals("")) { //necessary check, sometimes .split() creates an empty string, which then causes an error
                char firstChar = inputSplitElement.charAt(0);

                //check for valid first char
                boolean stringStartsWithVowelTehta = false;
                if (vowelTehtarOnCarrierSet.contains(firstChar)) {
                    stringStartsWithVowelTehta = true;
                }

                if (stringStartsWithVowelTehta && inputSplitElement.length() > 1) { //if valid 1st char AND if the snippet is 2 or more chars long
                    char[] splitElementArr = inputSplitElement.toCharArray();
                    char temp = splitElementArr[0];
                    splitElementArr[0] = splitElementArr[1];
                    splitElementArr[1] = temp;
                    result.append(splitElementArr); //need to use .toString()?
                } else {
                    result.append(inputSplitElement);
                }
            }
        }
        return result.toString();
    }

    public static String adjustCorrectTehtaForPrecedingTengwa(){

        return "";
    }

    public static String putTehtarOnSucceedingTengwar(String inputText) {
        String[] rawChars = new String[]{
                "`C1",
                "`C!",
                "`Cq",
                "`CQ",
                "`Ca",
                "`CA",
                "`Cz",
                "`CZ",
                "`C2",
                "`C@",
                "`Cw",
                "`CW",
                "`Cs",
                "`CS",
                "`Cx",
                "`CX",
                "`C3",
                "`Ce",
                "`Cd",
                "`Cc",
                "`C4",
                "`Cr",
                "`Cf",
                "`Cv",
                "`C5",
                "`Ct",
                "`Cg",
                "`Cb",
                "`C6",
                "`Cy",
                "`Ch",
                "`Cn",
                "`C7",
                "`Cu",
                "`Cj",
                "`Cm",
                "`C8",
                "`Ci",
                "`Ck",
                "`C,",
                "`C9",
                "`Co",
                "`Cl",
                "`C.",
                "`V1",
                "`V!",
                "`Vq",
                "`VQ",
                "`Va",
                "`VA",
                "`Vz",
                "`VZ",
                "`V2",
                "`V@",
                "`Vw",
                "`VW",
                "`Vs",
                "`VS",
                "`Vx",
                "`VX",
                "`V3",
                "`Ve",
                "`Vd",
                "`Vc",
                "`V4",
                "`Vr",
                "`Vf",
                "`Vv",
                "`V5",
                "`Vt",
                "`Vg",
                "`Vb",
                "`V6",
                "`Vy",
                "`Vh",
                "`Vn",
                "`V7",
                "`Vu",
                "`Vj",
                "`Vm",
                "`V8",
                "`Vi",
                "`Vk",
                "`V,",
                "`V9",
                "`Vo",
                "`Vl",
                "`V.",
                "`B1",
                "`B!",
                "`Bq",
                "`BQ",
                "`Ba",
                "`BA",
                "`Bz",
                "`BZ",
                "`B2",
                "`B@",
                "`Bw",
                "`BW",
                "`Bs",
                "`BS",
                "`Bx",
                "`BX",
                "`B3",
                "`Be",
                "`Bd",
                "`Bc",
                "`B4",
                "`Br",
                "`Bf",
                "`Bv",
                "`B5",
                "`Bt",
                "`Bg",
                "`Bb",
                "`B6",
                "`By",
                "`Bh",
                "`Bn",
                "`B7",
                "`Bu",
                "`Bj",
                "`Bm",
                "`B8",
                "`Bi",
                "`Bk",
                "`B,",
                "`B9",
                "`Bo",
                "`Bl",
                "`B.",
                "`N1",
                "`N!",
                "`Nq",
                "`NQ",
                "`Na",
                "`NA",
                "`Nz",
                "`NZ",
                "`N2",
                "`N@",
                "`Nw",
                "`NW",
                "`Ns",
                "`NS",
                "`Nx",
                "`NX",
                "`N3",
                "`Ne",
                "`Nd",
                "`Nc",
                "`N4",
                "`Nr",
                "`Nf",
                "`Nv",
                "`N5",
                "`Nt",
                "`Ng",
                "`Nb",
                "`N6",
                "`Ny",
                "`Nh",
                "`Nn",
                "`N7",
                "`Nu",
                "`Nj",
                "`Nm",
                "`N8",
                "`Ni",
                "`Nk",
                "`N,",
                "`N9",
                "`No",
                "`Nl",
                "`N.",
                "`M1",
                "`M!",
                "`Mq",
                "`MQ",
                "`Ma",
                "`MA",
                "`Mz",
                "`MZ",
                "`M2",
                "`M@",
                "`Mw",
                "`MW",
                "`Ms",
                "`MS",
                "`Mx",
                "`MX",
                "`M3",
                "`Me",
                "`Md",
                "`Mc",
                "`M4",
                "`Mr",
                "`Mf",
                "`Mv",
                "`M5",
                "`Mt",
                "`Mg",
                "`Mb",
                "`M6",
                "`My",
                "`Mh",
                "`Mn",
                "`M7",
                "`Mu",
                "`Mj",
                "`Mm",
                "`M8",
                "`Mi",
                "`Mk",
                "`M,",
                "`M9",
                "`Mo",
                "`Ml",
                "`M.",
                "`×1",
                "`×!",
                "`×q",
                "`×Q",
                "`×a",
                "`×A",
                "`×z",
                "`×Z",
                "`×2",
                "`×@",
                "`×w",
                "`×W",
                "`×s",
                "`×S",
                "`×x",
                "`×X",
                "`×3",
                "`×e",
                "`×d",
                "`×c",
                "`×4",
                "`×r",
                "`×f",
                "`×v",
                "`×5",
                "`×t",
                "`×g",
                "`×b",
                "`×6",
                "`×y",
                "`×h",
                "`×n"
        };

        String[] fixedChars = new String[]{
                "1E",
                "!D",
                "qE",
                "QE",
                "aE",
                "AE",
                "zE",
                "ZE",
                "2#",
                "@#",
                "w#",
                "W#",
                "s#",
                "S#",
                "x#",
                "X#",
                "3D",
                "eE",
                "dE",
                "cE",
                "4#",
                "r#",
                "f#",
                "v#",
                "5#",
                "t#",
                "g#",
                "b#",
                "6E",
                "yE",
                "hE",
                "nE",
                "7E",
                "uE",
                "j#",
                "m#",
                "iE",
                "iE",
                ",E",
                ",E",
                "9D",
                "oE",
                "lE",
                ".D",
                "1R",
                "!R",
                "qR",
                "QR",
                "aR",
                "AR",
                "zR",
                "ZR",
                "2$",
                "@$",
                "w$",
                "W$",
                "s$",
                "S$",
                "x$",
                "X$",
                "3R",
                "eR",
                "dR",
                "cR",
                "4$",
                "r$",
                "f$",
                "v$",
                "5$",
                "t$",
                "g$",
                "b$",
                "6R",
                "yR",
                "hR",
                "nR",
                "7R",
                "uR",
                "jR",
                "mR",
                "iR",
                "iR",
                ",R",
                ",R",
                "9V",
                "oR",
                "lR",
                ".R",
                "1T",
                "!T",
                "qT",
                "QT",
                "aT",
                "AT",
                "zT",
                "ZT",
                "2%",
                "@%",
                "w%",
                "W%",
                "s%",
                "S%",
                "x%",
                "X%",
                "3T",
                "eT",
                "dT",
                "cT",
                "4%",
                "r%",
                "f%",
                "v%",
                "5%",
                "t%",
                "g%",
                "b%",
                "6T",
                "yT",
                "hT",
                "nT",
                "7T",
                "uT",
                "j%",
                "m%",
                "iT",
                "iT",
                ",T",
                ",T",
                "9G",
                "oT",
                "lT",
                ".T",
                "1N",
                "!N",
                "qN",
                "QN",
                "aN",
                "AN",
                "zN",
                "ZN",
                "2Y",
                "@Y",
                "wY",
                "WY",
                "sY",
                "SY",
                "xY",
                "XY",
                "3N",
                "eN",
                "dN",
                "cN",
                "4Y",
                "rY",
                "fY",
                "vY",
                "5Y",
                "tY",
                "gY",
                "bY",
                "6N",
                "yN",
                "hN",
                "nN",
                "7N",
                "uN",
                "jY",
                "mY",
                "iN",
                "iN",
                ",N",
                ",N",
                "9N",
                "oY",
                "lN",
                ".N",
                "1M",
                "!M",
                "qJ",
                "QJ",
                "aM",
                "AU",
                "zJ",
                "ZU",
                "2&",
                "@&",
                "w&",
                "W&",
                "sU",
                "SU",
                "xU",
                "XU",
                "3M",
                "eM",
                "dU",
                "cU",
                "4&",
                "r&",
                "fU",
                "vU",
                "5&",
                "t&",
                "gU",
                "bU",
                "6M",
                "yM",
                "hM",
                "nM",
                "7J",
                "uJ",
                "jU",
                "mU",
                "iM",
                "iM",
                ",U",
                ",U",
                "9M",
                "oU",
                "lJ",
                ".M",
                "1Õ",
                "!Ö",
                "qÕ",
                "QÖ",
                "aÕ",
                "AÕ",
                "zÕ",
                "ZÕ",
                "2Ô",
                "@Ô",
                "wÔ",
                "WÔ",
                "sÔ",
                "SÔ",
                "xÔ",
                "XÔ",
                "3Ö",
                "eÖ",
                "dÕ",
                "cÕ",
                "4Ô",
                "rÔ",
                "fÔ",
                "vÔ",
                "5Ô",
                "t&",
                "gÔ",
                "bÔ",
                "6Õ",
                "yÕ",
                "hÕ",
                "nÕ"
        };

        return StringUtils.replaceEach(inputText, rawChars, fixedChars);
    }
}