package org.transliterator.Engine;

import org.apache.commons.lang3.StringUtils;

public class TgwTehtarTextMethods {
    //Here are the methods that work with the tehtar (the vowels)

    //StringUtils.replaceEach() takes as arguments one long string and two arrays of substrings
    //the method takes every instance of all elements of the first array and replaces it with the corresponding element from the second array
    //thus, all instances of "`C1" (element #1 from rawChars) will be replaced with  "1E"
    //the replacement is simultaneous, which is necessary to avoid bugs

    public static String tehtarizeVowels(String inputText) {
        //these replacements must be done simulateneously, not one after another, hence the use of StringUtils.replaceEach()
        String[] rawChars = new String[]{"]", "l", "`", "h", ".", "i"};
        String[] fixedChars = new String[]{"`C", "`V", "`B", "`N", "`M", "`×"};
        return StringUtils.replaceEach(inputText, rawChars, fixedChars);
    }

    public static String fixDiphtongs(String inputText) {
        //technically, any two vowels next to each other
        //this does not follow the dihptong rules in the Tengwar guides on the internet
        //this just creates diphtongs in a systematic manner
        /*
        aa ea ia oa ua ya
        ae ee ie oe ue ye
        ao eo io oo uo yo
        au eu iu ou uu yu
         */
        String[] rawChars = new String[]{
                "`C`C",                "`V`C",
                "`B`C",                "`N`C",
                "`M`C",                "`×`C",
                "`C`V",                "`V`V",
                "`B`V",                "`N`V",
                "`M`V",                "`×`V",
                "`C`N",                "`V`N",
                "`B`N",                "`N`N",
                "`M`N",                "`×`N",
                "`C`M",                "`B`M",
                "`V`M",                "`N`M",
                "`M`M",                "`×`M",
                "`B`B",                "`×`×"
        };

        String[] fixedChars = new String[]{
                "~C", "]R",
                "]T", "]N",
                "]J", "]Õ",
                "lE", "~V",
                "lT", "lN",
                "lJ", "lÕ",
                "hE", "hR",
                "hT", "~N",
                "hJ", "hÕ",
                ".E", ".T",
                ".R", ".N",
                "~M", ".Õ",
                "~B", "~×",

        };

        return StringUtils.replaceEach(inputText, rawChars, fixedChars);
    }

    public static String putTehtarOnSucceedingTengwar(String inputText) {
        //this method has quite a few lines, because the arrays were generated in the Chars Map Workbook.xlsx
        //it is the most foolproof way to put the vowel doodles (tehtar) in their right positions in the text
        //an algorithm that iterates over the chars, at this point in the transliteration process, is too difficult to write and requires too many checks
        //plus, using the spreadsheet allows for very easy adjustments in style
        //TODO consistent 'e' tehtar, must have same angle
        String[] rawChars = new String[]{
                "`C1",
                "`C!",
                "`Cq",
                "`CQ",
                "`Ca",
                "`CA",
                "`Cz",
                "`CZ",
                "`C2",
                "`C@",
                "`Cw",
                "`CW",
                "`Cs",
                "`CS",
                "`Cx",
                "`CX",
                "`C3",
                "`Ce",
                "`Cd",
                "`Cc",
                "`C4",
                "`Cr",
                "`Cf",
                "`Cv",
                "`C5",
                "`Ct",
                "`Cg",
                "`Cb",
                "`C6",
                "`Cy",
                "`Ch",
                "`Cn",
                "`C7",
                "`Cu",
                "`Cj",
                "`Cm",
                "`C8",
                "`Ci",
                "`Ck",
                "`C,",
                "`C9",
                "`Co",
                "`V1",
                "`V!",
                "`Vq",
                "`VQ",
                "`Va",
                "`VA",
                "`Vz",
                "`VZ",
                "`V2",
                "`V@",
                "`Vw",
                "`VW",
                "`Vs",
                "`VS",
                "`Vx",
                "`VX",
                "`V3",
                "`Ve",
                "`Vd",
                "`Vc",
                "`V4",
                "`Vr",
                "`Vf",
                "`Vv",
                "`V5",
                "`Vt",
                "`Vg",
                "`Vb",
                "`V6",
                "`Vy",
                "`Vh",
                "`Vn",
                "`V7",
                "`Vu",
                "`Vj",
                "`Vm",
                "`V8",
                "`Vi",
                "`Vk",
                "`V,",
                "`V9",
                "`Vo",
                "`B1",
                "`B!",
                "`Bq",
                "`BQ",
                "`Ba",
                "`BA",
                "`Bz",
                "`BZ",
                "`B2",
                "`B@",
                "`Bw",
                "`BW",
                "`Bs",
                "`BS",
                "`Bx",
                "`BX",
                "`B3",
                "`Be",
                "`Bd",
                "`Bc",
                "`B4",
                "`Br",
                "`Bf",
                "`Bv",
                "`B5",
                "`Bt",
                "`Bg",
                "`Bb",
                "`B6",
                "`By",
                "`Bh",
                "`Bn",
                "`B7",
                "`Bu",
                "`Bj",
                "`Bm",
                "`B8",
                "`Bi",
                "`Bk",
                "`B,",
                "`B9",
                "`Bo",
                "`N1",
                "`N!",
                "`Nq",
                "`NQ",
                "`Na",
                "`NA",
                "`Nz",
                "`NZ",
                "`N2",
                "`N@",
                "`Nw",
                "`NW",
                "`Ns",
                "`NS",
                "`Nx",
                "`NX",
                "`N3",
                "`Ne",
                "`Nd",
                "`Nc",
                "`N4",
                "`Nr",
                "`Nf",
                "`Nv",
                "`N5",
                "`Nt",
                "`Ng",
                "`Nb",
                "`N6",
                "`Ny",
                "`Nh",
                "`Nn",
                "`N7",
                "`Nu",
                "`Nj",
                "`Nm",
                "`N8",
                "`Ni",
                "`Nk",
                "`N,",
                "`N9",
                "`No",
                "`M1",
                "`M!",
                "`Mq",
                "`MQ",
                "`Ma",
                "`MA",
                "`Mz",
                "`MZ",
                "`M2",
                "`M@",
                "`Mw",
                "`MW",
                "`Ms",
                "`MS",
                "`Mx",
                "`MX",
                "`M3",
                "`Me",
                "`Md",
                "`Mc",
                "`M4",
                "`Mr",
                "`Mf",
                "`Mv",
                "`M5",
                "`Mt",
                "`Mg",
                "`Mb",
                "`M6",
                "`My",
                "`Mh",
                "`Mn",
                "`M7",
                "`Mu",
                "`Mj",
                "`Mm",
                "`M8",
                "`Mi",
                "`Mk",
                "`M,",
                "`M9",
                "`Mo",
                "`×1",
                "`×!",
                "`×q",
                "`×Q",
                "`×a",
                "`×A",
                "`×z",
                "`×Z",
                "`×2",
                "`×@",
                "`×w",
                "`×W",
                "`×s",
                "`×S",
                "`×x",
                "`×X",
                "`×3",
                "`×e",
                "`×d",
                "`×c",
                "`×4",
                "`×r",
                "`×f",
                "`×v",
                "`×5",
                "`×t",
                "`×g",
                "`×b",
                "`×6",
                "`×y",
                "`×h",
                "`×n",
                "`×7",
                "`×u",
                "`×j",
                "`×m",
                "`×8",
                "`×i",
                "`×k",
                "`×,",
                "`×9",
                "`×o"
        };

        String[] fixedChars = new String[]{
                "1E",
                "!D",
                "qE",
                "QE",
                "aE",
                "AE",
                "zE",
                "ZE",
                "2#",
                "@#",
                "w#",
                "W#",
                "s#",
                "S#",
                "x#",
                "X#",
                "3D",
                "eE",
                "dE",
                "cE",
                "4#",
                "r#",
                "f#",
                "v#",
                "5#",
                "t#",
                "g#",
                "b#",
                "6E",
                "yE",
                "hE",
                "nE",
                "7E",
                "uE",
                "j#",
                "m#",
                "iE",
                "iE",
                ",E",
                ",E",
                "9D",
                "oE",
                "1R",
                "!R",
                "qR",
                "QR",
                "aR",
                "AR",
                "zR",
                "ZR",
                "2R",
                "@R",
                "wR",
                "WR",
                "sR",
                "SR",
                "xR",
                "XR",
                "3R",
                "eR",
                "dR",
                "cR",
                "4R",
                "rR",
                "fR",
                "vR",
                "5R",
                "tR",
                "gR",
                "bR",
                "6R",
                "yR",
                "hR",
                "nR",
                "7R",
                "uR",
                "jR",
                "mR",
                "iV",
                "iV",
                ",V",
                ",V",
                "9V",
                "oR",
                "1T",
                "!T",
                "qT",
                "QT",
                "aT",
                "AT",
                "zT",
                "ZT",
                "2%",
                "@%",
                "w%",
                "W%",
                "s%",
                "S%",
                "x%",
                "X%",
                "3T",
                "eT",
                "dT",
                "cT",
                "4%",
                "r%",
                "f%",
                "v%",
                "5%",
                "t%",
                "g%",
                "b%",
                "6T",
                "yT",
                "hT",
                "nT",
                "7T",
                "uT",
                "j%",
                "m%",
                "iT",
                "iT",
                ",T",
                ",T",
                "9G",
                "oT",
                "1N",
                "!N",
                "qN",
                "QN",
                "aN",
                "AN",
                "zN",
                "ZN",
                "2Y",
                "@Y",
                "wY",
                "WY",
                "sY",
                "SY",
                "xY",
                "XY",
                "3N",
                "eN",
                "dN",
                "cN",
                "4Y",
                "rY",
                "fY",
                "vY",
                "5Y",
                "tY",
                "gY",
                "bY",
                "6N",
                "yN",
                "hN",
                "nN",
                "7N",
                "uN",
                "jY",
                "mY",
                "iN",
                "iN",
                ",N",
                ",N",
                "9N",
                "oY",
                "1M",
                "!M",
                "qJ",
                "QJ",
                "aM",
                "AU",
                "zJ",
                "ZU",
                "2&",
                "@&",
                "w&",
                "W&",
                "sU",
                "SU",
                "xU",
                "XU",
                "3M",
                "eM",
                "dU",
                "cU",
                "4&",
                "r&",
                "fU",
                "vU",
                "5&",
                "t&",
                "gU",
                "bU",
                "6M",
                "yM",
                "hM",
                "nM",
                "7J",
                "uJ",
                "jU",
                "mU",
                "iM",
                "iM",
                ",U",
                ",U",
                "9M",
                "oU",
                "1Õ",
                "!Ö",
                "qÕ",
                "QÖ",
                "aÕ",
                "AÕ",
                "zÕ",
                "ZÕ",
                "2Ô",
                "@Ô",
                "wÔ",
                "WÔ",
                "sÔ",
                "SÔ",
                "xÔ",
                "XÔ",
                "3Ö",
                "eÖ",
                "dÕ",
                "cÕ",
                "4Ô",
                "rÔ",
                "fÔ",
                "vÔ",
                "5Ô",
                "t&",
                "gÔ",
                "bÔ",
                "6Õ",
                "yÕ",
                "hÕ",
                "nÕ",
                "7Õ",
                "uÕ",
                "jÔ",
                "mÔ",
                "iÕ",
                "iÕ",
                ",Õ",
                ",Õ",
                "9Ö",
                "oÕ"
        };

        return StringUtils.replaceEach(inputText, rawChars, fixedChars);
    }
}